# stage 1

FROM  python:3.10-slim AS builder

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt --target=/app/deps


#stage 2

FROM gcr.io/distroless/python3-debian12

WORKDIR /app

COPY --from=builder /app/deps /app/deps
COPY --from=builder /app .

EXPOSE 80

ENV PYTHONPATH="/app/deps"

CMD ["run.py"]

